import { IRunes } from '../types';

export const runes: IRunes[] = [
  {
    name: 'el',
    level: 11,
    image: require('@assets/images/runes/el.png'),
    owned: false,
  },
  {
    name: 'eld',
    level: 11,
    image: require('@assets/images/runes/eld.png'),
    owned: false,
  },
  {
    name: 'tir',
    level: 13,
    image: require('@assets/images/runes/tir.png'),
    owned: false,
  },
  {
    name: 'nef',
    level: 13,
    image: require('@assets/images/runes/nef.png'),
    owned: false,
  },
  {
    name: 'eth',
    level: 15,
    image: require('@assets/images/runes/eth.png'),
    owned: false,
  },
  {
    name: 'ith',
    level: 15,
    image: require('@assets/images/runes/ith.png'),
    owned: false,
  },
  {
    name: 'tal',
    level: 17,
    image: require('@assets/images/runes/tal.png'),
    owned: false,
  },
  {
    name: 'ral',
    level: 19,
    image: require('@assets/images/runes/ral.png'),
    owned: false,
  },
  {
    name: 'ort',
    level: 21,
    image: require('@assets/images/runes/ort.png'),
    owned: false,
  },
  {
    name: 'thul',
    level: 23,
    image: require('@assets/images/runes/thul.png'),
    owned: false,
  },
  {
    name: 'amn',
    level: 25,
    image: require('@assets/images/runes/amn.png'),
    owned: false,
  },
  {
    name: 'sol',
    level: 27,
    image: require('@assets/images/runes/sol.png'),
    owned: false,
  },
  {
    name: 'shael',
    level: 29,
    image: require('@assets/images/runes/shael.png'),
    owned: false,
  },
  {
    name: 'dol',
    level: 31,
    image: require('@assets/images/runes/dol.png'),
    owned: false,
  },
  {
    name: 'hel',
    level: 0,
    image: require('@assets/images/runes/hel.png'),
    owned: false,
  },
  {
    name: 'io',
    level: 35,
    image: require('@assets/images/runes/io.png'),
    owned: false,
  },
  {
    name: 'lum',
    level: 37,
    image: require('@assets/images/runes/lum.png'),
    owned: false,
  },
  {
    name: 'ko',
    level: 39,
    image: require('@assets/images/runes/ko.png'),
    owned: false,
  },
  {
    name: 'fal',
    level: 41,
    image: require('@assets/images/runes/fal.png'),
    owned: false,
  },
  {
    name: 'lem',
    level: 43,
    image: require('@assets/images/runes/lem.png'),
    owned: false,
  },
  {
    name: 'pul',
    level: 45,
    image: require('@assets/images/runes/pul.png'),
    owned: false,
  },
  {
    name: 'um',
    level: 47,
    image: require('@assets/images/runes/um.png'),
    owned: false,
  },
  {
    name: 'mal',
    level: 49,
    image: require('@assets/images/runes/mal.png'),
    owned: false,
  },
  {
    name: 'ist',
    level: 51,
    image: require('@assets/images/runes/ist.png'),
    owned: false,
  },
  {
    name: 'gul',
    level: 53,
    image: require('@assets/images/runes/gul.png'),
    owned: false,
  },
  {
    name: 'vex',
    level: 55,
    image: require('@assets/images/runes/vex.png'),
    owned: false,
  },
  {
    name: 'ohm',
    level: 57,
    image: require('@assets/images/runes/ohm.png'),
    owned: false,
  },
  {
    name: 'lo',
    level: 59,
    image: require('@assets/images/runes/lo.png'),
    owned: false,
  },
  {
    name: 'sur',
    level: 61,
    image: require('@assets/images/runes/sur.png'),
    owned: false,
  },
  {
    name: 'ber',
    level: 63,
    image: require('@assets/images/runes/ber.png'),
    owned: false,
  },
  {
    name: 'jah',
    level: 65,
    image: require('@assets/images/runes/jah.png'),
    owned: false,
  },
  {
    name: 'cham',
    level: 67,
    image: require('@assets/images/runes/cham.png'),
    owned: false,
  },
  {
    name: 'zod',
    level: 69,
    image: require('@assets/images/runes/zod.png'),
    owned: false,
  },
];
